version: '3'

services:
# PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - C:\\tmp\\postgres-docker:/var/lib/postgresql/data
      - ./infra/sql:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "max_connections=1000"]

  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      NODE_ENV: production
    depends_on:
      - postgres